name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: echo "Hello world"

      - name: Get Date  
        run: date
      
      - name: Get list
        run: ls -l
      # run: |
      #   echo "Hello world"
